set dotenv-load := true

migrations_dir := "database/migrations"
gen_dir := "internal/gen"
gen_swagger_out := "internal/gen/http/v1"

default:
    @just --list

install-tools:
    @go install github.com/ogen-go/ogen/cmd/ogen@v1.18.0
    @go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1
    @go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1

generate: swagger sqlc

swagger:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p {{ gen_swagger_out }}
    ogen --target {{ gen_swagger_out }} --package http_v1 --config api/http/v1/.ogen.yml --clean api/http/v1/api.yaml
    cd ../.. && go run ./_misc/openapi-handler-gen/ services/auth/{{ gen_swagger_out }}/openapi_handler.go http_v1 openapi.yaml

sqlc:
    @cd database && sqlc generate

migrate-up:
    migrate -path {{ migrations_dir }} -database "${DATABASE_URL}" up

migrate-down:
    migrate -path {{ migrations_dir }} -database "${DATABASE_URL}" down 1

run:
    go run ./cmd
