set dotenv-load := true

migrations_dir := "database/migrations"
gen_dir := "internal/gen/http/v1"

default:
    @just --list

install-tools:
    @go install github.com/ogen-go/ogen/cmd/ogen@v1.18.0
    @go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1
    @go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1

generate: swagger sqlc

swagger:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p {{ gen_dir }}
    ogen --target {{ gen_dir }} --package http_v1 --config api/http/v1/.ogen.yml --clean api/http/v1/api.yaml
    cd ../..
    go run ./_misc/openapi-handler-gen/ services/learning/{{ gen_dir }}/openapi_handler.go http_v1 openapi.yaml
    go run ./_misc/handler-stub-gen/ services/learning/internal/gen/http/v1/oas_server_gen.go services/learning/internal/handler github.com/even-app/even-app/services/learning/internal/gen/http/v1 http_v1

sqlc:
    @cd database && sqlc generate

migrate-up:
    migrate -path {{ migrations_dir }} -database "${DATABASE_URL}" up

migrate-down:
    migrate -path {{ migrations_dir }} -database "${DATABASE_URL}" down 1

run:
    go run ./cmd
