// Code generated by handler-stub-gen. DO NOT EDIT.
// Implement business logic in http_api.go (or other hand-written files), then re-run `just swagger`.

package handler

// All Handler methods are implemented in hand-written files.
